name: 'Setup My Project'
description: 'Configura Node, instala dependencias y cachea todo'

inputs:
  node-version:
    description: 'Versión de Node'
    required: false
    default: '20'

outputs:
  cache-hit:
    description: 'Si hubo hit en el cache'
    value: ${{ steps.npm-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'                    # Mejor forma recomendada

    - name: Instalar dependencias
      shell: bash
      run: |
        npm ci || npm install