name: 06 - Secretos y Variables de Entorno

# Variables a nivel de Workflow (disponibles en todo el workflow)
env:
  ENTORNO_GLOBAL: "desarrollo"

on: [push, pull_request]

jobs:
  probar_configuracion:
    runs-on: ubuntu-latest
    # Variable a nivel de Job
    env:
      ENTORNO_JOB: "testing"
      
    steps:
      - name: 1. Variables de entorno normales
        env:
          ENTORNO_STEP: "local" # Variable a nivel de Step
        run: |
          echo "Global: $ENTORNO_GLOBAL"
          echo "Job: $ENTORNO_JOB"
          echo "Step: $ENTORNO_STEP"

      - name: 2. Usando el GITHUB_TOKEN (Secreto automático)
        # GitHub inyecta este token automáticamente. Sirve para llamar a la API de GitHub.
        run: |
          echo "El token existe y tiene longitud: ${#GITHUB_TOKEN}"
          # Nota: No intentes hacer echo $GITHUB_TOKEN completo, GitHub lo enmascarará.
          
      - name: 3. Usando nuestros Secretos personalizados
        env:
          API_KEY: ${{ secrets.MI_API_KEY_FALSA }}
        run: |
          echo "Intentando imprimir el secreto..."
          echo "Mi API Key es: $API_KEY"
          # ¡Observa los logs! GitHub reemplazará el valor real por '***'.
          
      - name: 4. El peligro de los secretos (Manipulación)
        run: |
          # Si manipulas el string, GitHub NO lo enmascarará. ¡Cuidado con esto en producción!
          echo "Secreto manipulado: ${{ secrets.MI_API_KEY_FALSA }}-sufijo"