name: 16 - Usando Composite Action

on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar entorno
        id: setup
        uses: ./.github/actions/setup-my-project
        with:
          node-version: '20'

      - name: ¿Hubo cache?
        run: echo "Cache hit? ${{ steps.setup.outputs.cache-hit }}"

      - name: Correr tests
        run: npm test || echo "No hay tests definidos"